project_name: frp

builds:
  - id: frpc
    main: ./cmd/frpc
    binary: frpc
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
    ldflags:
      - -s -w
    tags:
      - frpc
      - noweb

  - id: frps
    main: ./cmd/frps
    binary: frps
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
    ldflags:
      - -s -w
    tags:
      - frps
      - noweb

archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - frpc
      - frps

checksum:
  name_template: '{{ .ProjectName }}_sha256_checksums.txt'
  algorithm: sha256

release:
  github:
    owner: qq761861
    name: frp
  draft: false
